services:
  - type: web
    name: pitch-deck-backend
    env: python
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: pitch-deck-db
          property: connectionString
      - key: CRUNCHBASE_API_KEY
        sync: false  # Add manually in Render Dashboard
      - key: FRONTEND_URL
        value: https://pitchdeck.onrender.com
  - type: web
    name: pitch-deck-frontend
    env: static
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://pitch-deck-backend.onrender.com
  - type: pserv  # Background worker for scheduled tasks
    name: pitch-deck-cron
    env: python
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python scrape.py
    #schedule: "0 */6 * * *"  # Run every 6 hours (12am, 6am, 12pm, 6pm)
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: pitch-deck-db
          property: connectionString
      - key: CRUNCHBASE_API_KEY
        sync: false
databases:
  - name: pitch-deck-db
    databaseName: pitch_deck_db